server:
  port: ${SERVER_PORT:3000}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}
  config:
    import: optional:file:.env[.properties]
  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Debug configuration
debug: true # Enables debug mode for Spring Boot

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG # Replace with your package name
    org.springframework.security: DEBUG # For security debugging
    org.hibernate: DEBUG # For Hibernate debugging
    org.springframework.web: DEBUG # For web request debugging
    org.springframework.jdbc: DEBUG # For database debugging
