server:
  port: 5000

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/v1/restaurants/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
  instance:
    prefer-ip-address: true
logging:
  charset:
    console: UTF-8
  level:
    'org.springframework.cloud.gateway': DEBUG
