server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka
  instance:
    prefer-ip-address: true

debug: true # Enables debug mode for Spring Boot

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG # Replace with your package name
    org.springframework.security: DEBUG # For security debugging
    org.hibernate: DEBUG # For Hibernate debugging
    org.springframework.web: DEBUG # For web request debugging
    org.springframework.jdbc: DEBUG # For database debugging
