server:
  port: ${SERVER_PORT}
  address: 0.0.0.0

spring:
  config:
    import: optional:dotenv:/.env
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          default-label: ${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL}
